<a href="https://colab.research.google.com/github/KValim/Projetcs/blob/main/FIAP/working%20with%20python/lista%202/Working_With_Python_Lista_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1) Escreva um programa que lê do teclado e registra em uma matriz (3x6), a receita de 3 (três)
empresas do último semestre (6 meses)
Após ler a receita de cada empresa mes a mes, seu programa deve então retornar a Média e o
Desvio Padrão Populacional das receitas do semestre para cada uma das empresas



In [ ]:
empresas = ['E1', 'E2', 'E3']
meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun']

ocupacao = np.zeros((len(empresas),len(meses)))

for index_cidade in range(len(empresas)):
  for index_dia in range(len(meses )):
    text = 'Receita ' + str(meses[index_dia]) + ' -> ' + str(empresas[index_cidade]) + ': '
    ocupacao[index_cidade, index_dia] = float(input(text))

print('\n',ocupacao)

f = 0
for e in empresas:
  print('\nEMPRESA\t', e)
  print('Média\t\t',round(np.mean(ocupacao[f,:]),2))
  print('Desvio padrão\t', round(np.std(ocupacao[f,:]),2))
  f+=1

Receita jan -> E1: 1
Receita fev -> E1: 3
Receita mar -> E1: 4
Receita abr -> E1: 2.5
Receita mai -> E1: 3
Receita jun -> E1: 5
Receita jan -> E2: 7
Receita fev -> E2: 5
Receita mar -> E2: 3
Receita abr -> E2: 1
Receita mai -> E2: 2
Receita jun -> E2: 0.2
Receita jan -> E3: 22
Receita fev -> E3: 43
Receita mar -> E3: 55
Receita abr -> E3: 60
Receita mai -> E3: 76
Receita jun -> E3: 89

 [[ 1.   3.   4.   2.5  3.   5. ]
 [ 7.   5.   3.   1.   2.   0.2]
 [22.  43.  55.  60.  76.  89. ]]

EMPRESA	 E1
Média		 3.08
Desvio padrão	 1.24

EMPRESA	 E2
Média		 3.03
Desvio padrão	 2.34

EMPRESA	 E3
Média		 57.5
Desvio padrão	 21.67


2) Crie um programa no qual você deve ler do teclado todas as compras de 6 (seis) ações/ativos
realizadas em um dia, coletando informações de preço e quantidade para cada uma. Armazene
essa informação em uma matriz 1x6 com os preços.
Já as quantidades armazenadas em uma outra matriz 6x1.
De posse dessas duas informações realize o cálculo final do montante em dinheiro de ativos
adquiridos neste dia para sua carteira.



In [ ]:
matriz_precos = np.zeros((6,1))
matriz_qtd = np.zeros((1,6))

for acao in range(6):
  print(f'Informações sobre compra da ação {acao+1}')
  matriz_qtd[0,acao] = int(input(f'\tQuantidade Lotes Adquiridos: '))
  matriz_precos[acao,0] = float(input(f'\tPreço de Aquisição: '))
  print('\n')


print(f'O valor dos seus ativos é de R$ {(matriz_qtd @ matriz_precos)[0,0]}')

Informações sobre compra da ação 1
	Quantidade Lotes Adquiridos: 4
	Preço de Aquisição: 2


Informações sobre compra da ação 2
	Quantidade Lotes Adquiridos: 5
	Preço de Aquisição: 67


Informações sobre compra da ação 3
	Quantidade Lotes Adquiridos: 1
	Preço de Aquisição: 554


Informações sobre compra da ação 4
	Quantidade Lotes Adquiridos: 66
	Preço de Aquisição: 2


Informações sobre compra da ação 5
	Quantidade Lotes Adquiridos: 1
	Preço de Aquisição: 100


Informações sobre compra da ação 6
	Quantidade Lotes Adquiridos: 250
	Preço de Aquisição: 0.3


O valor dos seus ativos é de R$ 1204.0


3) Uma corretora que trabalha com 3 ativos principais VALE5, PETR4 e BBDC4, gostaria de
registrar os rendimentos da semana em uma matriz 5x3. Crie um programa que lê do teclado dia
a dia o rendimento de cada um dos 3 ativos. Em seguida o programa deve fazer o cálculo de
rendimento acumulado de cada ativo na semana. E por fim, apresenta o rendimento médio total
do fundo.



In [ ]:
nome_acoes = ['VALE5', 'PETR4', 'BBDC4']
dias_semana = ['segunda', 'terça', 'quarta', 'quinta', 'sexta']

rendimentos = np.zeros((len(dias_semana),len(nome_acoes)))

for index_acao in range(len(nome_acoes)):
  for index_dia in range(len(dias_semana)):
    text = 'Rendimento da ação ' + str(nome_acoes[index_acao]) + ' na ' + str(dias_semana[index_dia]) + ': '
    rendimentos[index_dia, index_acao] = float(input(text))

for index_acao in range(len(nome_acoes)):
  fator_multiplicacao = 1
  for index_dia in range(len(dias_semana)):
    fator_multiplicacao = fator_multiplicacao*(1+rendimentos[index_dia, index_acao])

  print('\n')
  print(nome_acoes[index_acao])
  print('Rendimento total na semana: ', round(fator_multiplicacao - 1, 2)*100, '%')

Rendimento da ação VALE5 na segunda: 0.1
Rendimento da ação VALE5 na terça: 0.04
Rendimento da ação VALE5 na quarta: -0.06
Rendimento da ação VALE5 na quinta: 0.2
Rendimento da ação VALE5 na sexta: 0.1
Rendimento da ação PETR4 na segunda: -0.1
Rendimento da ação PETR4 na terça: -0.1
Rendimento da ação PETR4 na quarta: -0.05
Rendimento da ação PETR4 na quinta: 0
Rendimento da ação PETR4 na sexta: 0.1
Rendimento da ação BBDC4 na segunda: 0.3
Rendimento da ação BBDC4 na terça: 0.2
Rendimento da ação BBDC4 na quarta: 0.5
Rendimento da ação BBDC4 na quinta: 0.4
Rendimento da ação BBDC4 na sexta: -0.5


VALE5
Rendimento total na semana:  42.0 %


PETR4
Rendimento total na semana:  -15.0 %


BBDC4
Rendimento total na semana:  64.0 %


4) As 3 principais cidades brasileiras estão preocupadas com a taxa de ocupação de hospitais
durante o COVID. Crie um programa que lê do teclado dia a dia para cada cidade e registra em
uma matriz 7x3 a taxa de ocupação dos hospitais dessas 3 cidades nos última semana (7 dias)
Se programa deve apresentar então o mínimo, máximo e média de ocupação dos leitos para
cada cidade.


In [ ]:
cidades = ['C1', 'C2', 'C3']
dias_semana = ['segunda', 'terça', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo']

ocupacao = np.zeros((len(dias_semana),len(cidades)))

for index_cidade in range(len(cidades)):
  for index_dia in range(len(dias_semana)):
    text = 'Taxa de ocupação ' + str(cidades[index_cidade]) + ' -> ' + str(dias_semana[index_dia]) + ': '
    ocupacao[index_dia, index_cidade] = float(input(text))

print('\n',ocupacao)

f = 0
for c in cidades:
  print('\nCIDADE\t', c)
  print('Mínimo\t', min(ocupacao[:,f]))
  print('Máximo\t', max(ocupacao[:,f]))
  print('Média\t',round(np.mean(ocupacao[:,f]),2))
  f+=1

Taxa de ocupação C1 -> segunda: 0.1
Taxa de ocupação C1 -> terça: 0.2
Taxa de ocupação C1 -> quarta: 0.34
Taxa de ocupação C1 -> quinta: 0.5
Taxa de ocupação C1 -> sexta: 0.7
Taxa de ocupação C1 -> sabado: 0.6
Taxa de ocupação C1 -> domingo: 0.9
Taxa de ocupação C2 -> segunda: 0.5
Taxa de ocupação C2 -> terça: 0.8
Taxa de ocupação C2 -> quarta: 0.97
Taxa de ocupação C2 -> quinta: 1
Taxa de ocupação C2 -> sexta: 1
Taxa de ocupação C2 -> sabado: 0.95
Taxa de ocupação C2 -> domingo: 0.9
Taxa de ocupação C3 -> segunda: 0
Taxa de ocupação C3 -> terça: 0
Taxa de ocupação C3 -> quarta: 0.1
Taxa de ocupação C3 -> quinta: 0.2
Taxa de ocupação C3 -> sexta: 0.12
Taxa de ocupação C3 -> sabado: 0.07
Taxa de ocupação C3 -> domingo: 0.3

 [[0.1  0.5  0.  ]
 [0.2  0.8  0.  ]
 [0.34 0.97 0.1 ]
 [0.5  1.   0.2 ]
 [0.7  1.   0.12]
 [0.6  0.95 0.07]
 [0.9  0.9  0.3 ]]

CIDADE	 C1
Mínimo	 0.1
Máximo	 0.9
Média	 0.48

CIDADE	 C2
Mínimo	 0.5
Máximo	 1.0
Média	 0.87

CIDADE	 C3
Mínimo	 0.0
Máximo	 0.3
Média	 